kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: http
      port: 4180
      targetPort: 4180
      protocol: TCP
