apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  clientId: {{ .Values.secrets.client_id | b64enc}}
  clientSecret: {{ .Values.secrets.client_secret | b64enc}}
  {{- if .Values.secrets.cookie_secret }}
  cookieSecret: {{ .Values.secrets.cookie_secret | b64enc }}
  {{- end }}
