{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "fullname" . }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ template "fullname" . }}-tls
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: {{ template "fullname" . }}-service
          servicePort: 4180
{{- end -}}
