apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-cm
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ $nodeCount := .Values.replicas | int }}
data:
  start.sh: |
     /oklog ingeststore \
      -api tcp://0.0.0.0:3000 \
      -ingest.fast tcp://0.0.0.0:3001 \
      -ingest.durable tcp://0.0.0.0:3002 \
      -ingest.bulk tcp://0.0.0.0:3003 \
      -debug \
      -cluster tcp://$KUBERNETES_POD_IP:3009 \
      -store.segment-target-size 1000000 \
      -store.segment-replication-factor 2 \
      -store.segment-retain 30m \
      -store.segment-purge 5m \
     {{- range $i := until $nodeCount }}
      -peer {{ template "fullname" $ }}-{{$i}}.{{ template "fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:3009 \
     {{- end }}
