# Inspired by https://github.com/kubernetes/charts/blob/master/stable/minio/values.yaml

# Docker image
image: "oklog/oklog"
imageTag: v0.2.1
imagePullPolicy: "Always"

replicas: 4

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

ingress:
  enabled: false
  host: "oklog.example.com"
  annotations: {}
  tls: []

# Configure
resources:
  requests:
    memory: 128Mi
    cpu: 0.1
